server:
  port: 8085

spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8090
    #Connect to the config server, and get the configuration from there.