eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka  # Address of the Eureka server.

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa # Default admin user in H2.
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true