server:
  port: 8090

spring:
  application:
    name: config

  profiles:
    active:
      - native # Allows other apps to get configurations from config directory.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka  # Address of the Eureka server.
